# Generated by Django 2.0 on 2017-12-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_license_available_contents'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OL', 'Open Launcher'), ('CL', 'Close Launcher'), ('OC', 'Open Content'), ('CC', 'Close Content'), ('ER', 'Error')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.Content')),
                ('content_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.ContentVersion')),
                ('launcher_version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.LauncherVersion')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='registration.License')),
            ],
        ),
    ]
