# Generated by Django 2.0 on 2017-12-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '로그', 'verbose_name_plural': '로그'},
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.Content', verbose_name='콘텐츠'),
        ),
        migrations.AlterField(
            model_name='log',
            name='content_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.ContentVersion', verbose_name='콘텐츠 버전'),
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='추가 설명'),
        ),
        migrations.AlterField(
            model_name='log',
            name='launcher_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.LauncherVersion', verbose_name='런처 버전'),
        ),
        migrations.AlterField(
            model_name='log',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='registration.License', verbose_name='라이센스'),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='시각'),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('OL', 'Open Launcher'), ('CL', 'Close Launcher'), ('OC', 'Open Content'), ('CC', 'Close Content'), ('ER', 'Error')], max_length=2, verbose_name='타입'),
        ),
    ]
