# Generated by Django 2.0 on 2017-12-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20171212_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='content',
        ),
    ]
