# Generated by Django 2.0 on 2017-12-12 06:02

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='이름')),
            ],
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '콘텐츠', 'verbose_name_plural': '콘텐츠'},
        ),
        migrations.AlterModelOptions(
            name='contentversion',
            options={'verbose_name': '콘텐츠 버전', 'verbose_name_plural': '콘텐츠 버전'},
        ),
        migrations.AlterModelOptions(
            name='launcherversion',
            options={'verbose_name': '런처 버전', 'verbose_name_plural': '런처 버전'},
        ),
        migrations.AddField(
            model_name='content',
            name='asset_bundle_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Asset Bundle 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentversion',
            name='asset_bundle_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Asset Bundle 번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='content',
            name='scene_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Unity Scene 이름'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='content.Content', verbose_name='콘텐츠'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='download_url',
            field=models.URLField(unique=True, verbose_name='다운로드 URL'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='minimum_launcher_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.LauncherVersion', verbose_name='최소 런처 버전'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='업데이트 시간'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='version_number',
            field=models.CharField(max_length=8, unique=True, validators=[content.models.version_number_validator], verbose_name='버전명'),
        ),
        migrations.AlterField(
            model_name='launcherversion',
            name='download_url',
            field=models.URLField(unique=True, verbose_name='다운로드 URL'),
        ),
        migrations.AlterField(
            model_name='launcherversion',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='업데이트 시간'),
        ),
        migrations.AlterField(
            model_name='launcherversion',
            name='version_number',
            field=models.CharField(max_length=8, unique=True, validators=[content.models.version_number_validator], verbose_name='버전명'),
        ),
        migrations.AlterUniqueTogether(
            name='contentversion',
            unique_together={('content', 'asset_bundle_number')},
        ),
        migrations.AddField(
            model_name='content',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='content.App', verbose_name='앱'),
            preserve_default=False,
        ),
    ]
