# Generated by Django 2.0 on 2017-12-22 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20171212_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='content.App', verbose_name='앱'),
        ),
    ]
