# Generated by Django 2.0 on 2018-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20171222_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='launcherversion',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
