# Generated by Django 2.0 on 2018-01-17 02:33

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180117_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='content',
            name='asset_bundle_name',
            field=models.CharField(max_length=50, verbose_name='Asset Bundle 이름'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='content',
            name='scene_name',
            field=models.CharField(max_length=50, verbose_name='Unity Scene 이름'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='download_url',
            field=models.URLField(verbose_name='다운로드 URL'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='version_number',
            field=models.CharField(max_length=8, validators=[content.models.version_number_validator], verbose_name='버전명'),
        ),
        migrations.AlterField(
            model_name='launcherversion',
            name='download_url',
            field=models.URLField(verbose_name='다운로드 URL'),
        ),
        migrations.AlterField(
            model_name='launcherversion',
            name='version_number',
            field=models.CharField(max_length=8, validators=[content.models.version_number_validator], verbose_name='버전명'),
        ),
    ]
