# Generated by Django 2.0 on 2017-12-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20171212_1502'),
        ('registration', '0002_license_available_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': '기관', 'verbose_name_plural': '기관'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': '라이센스', 'verbose_name_plural': '라이센스'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='license',
            name='available_apps',
            field=models.ManyToManyField(blank=True, related_name='available_licenses', to='content.App', verbose_name='사용 가능한 앱'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='기관명'),
        ),
        migrations.AlterField(
            model_name='license',
            name='available_contents',
            field=models.ManyToManyField(blank=True, related_name='available_licenses', to='content.Content', verbose_name='사용 가능한 콘텐츠'),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='license',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='사용 중지'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expire_time',
            field=models.DateTimeField(verbose_name='라이센스 만료 시각'),
        ),
        migrations.AlterField(
            model_name='license',
            name='for_test',
            field=models.BooleanField(default=False, verbose_name='테스트용 라이센스'),
        ),
        migrations.AlterField(
            model_name='license',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='registration.Institution', verbose_name='기관'),
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='라이센스 키'),
        ),
        migrations.AlterField(
            model_name='license',
            name='last_active_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 시각'),
        ),
        migrations.AlterField(
            model_name='license',
            name='register_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 등록 시각'),
        ),
        migrations.AlterField(
            model_name='license',
            name='unity_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기기별 Unity 키'),
        ),
    ]
