# Generated by Django 2.0 on 2017-12-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171212_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='local_max_count',
            field=models.PositiveIntegerField(default=20, verbose_name='오프라인 시 최대 사용 가능 횟수'),
        ),
    ]
