# Generated by Django 2.0 on 2018-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_license_local_max_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
